import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import styles from '@/styles/portfolio.module.css';

const wa = 'https://wa.me/32451032046?text=' + encodeURIComponent('Hallo, ik heb jullie portfolio bekeken en ik wil graag meer weten over een website voor mijn bedrijf.');
const wks = 'https://wksperformance.be';
const vanloon = 'https://van-loon-badkamers.vercel.app/';
function External({href,children,className}: {href:string;children:React.ReactNode;className?:string}) {return <a href={href} target="_blank" rel="noopener noreferrer" className={className}>{children}<span aria-hidden="true">↗</span></a>}
function Shot({name,alt,width,height,priority=false}: {name:string;alt:string;width:number;height:number;priority?:boolean}) {return <Image src={'/portfolio/'+name+'.webp'} alt={alt} width={width} height={height} priority={priority} unoptimized className={styles.shot}/>}
export default function Portfolio() { return <div className={styles.page}>
<Head><title>Ons werk | Websites voor lokale bedrijven | Moza Systems</title><meta name="description" content="Bekijk de websites van WKS Performance en het concept voor Van Loon Badkamers. Moza Systems bouwt websites voor lokale bedrijven, met hulp bij de technische opzet."/><meta name="viewport" content="width=device-width, initial-scale=1"/><link rel="canonical" href="https://www.mozasystems.com/portfolio"/><meta property="og:title" content="Ons werk | Moza Systems"/><meta property="og:description" content="Websites voor lokale bedrijven. Bekijk ons werk en bespreek jouw website."/><meta property="og:locale" content="nl_BE"/><meta name="theme-color" content="#ffffff"/><link rel="icon" href="/icon.png"/></Head>
<a className={styles.skip} href="#inhoud">Naar de inhoud</a>
<header className={styles.header}><Link href="/portfolio" aria-label="Moza Systems, portfolio" className={styles.logo}><Image src="/portfolio/moza-original.png" alt="Moza Systems" width={2172} height={724} sizes="184px" priority/></Link><nav aria-label="Hoofdnavigatie"><a href="#werk">Ons werk</a><a href="#website">Jouw website</a><External href={wa}>WhatsApp</External></nav></header>
<main id="inhoud">
<section className={styles.intro}><div><p className={styles.introLabel}>Moza Systems · Websites voor lokale bedrijven</p><h1>Een website die laat zien<br/>wat je zaak te bieden heeft.</h1></div><div className={styles.introAside}><p>Je werk in beeld. Je aanbod duidelijk.<br/>En een eenvoudige manier om je te bereiken.</p><a href="#werk">Bekijk onze websites <span aria-hidden="true">↓</span></a></div></section>
<div className={styles.workIndex} id="werk"><h2>Ons werk</h2><span>01 — 02</span></div>
<article className={styles.wks} aria-labelledby="wks-title">
<div className={styles.projectHeading}><div><span className={styles.number}>01</span><h3 id="wks-title">WKS Performance</h3><span className={styles.status}>Eigen onderneming · Online</span></div><External href={wks}>Bekijk de website</External></div>
<div className={styles.wksCanvas}><figure className={styles.wksDesktop}><div className={styles.browser} aria-hidden="true"><span>•••</span><span>wksperformance.be</span><span>↗</span></div><Shot name="wks-desktop" alt="De startpagina van WKS Performance: extra voetbaltraining naast je club" width={1440} height={612} priority/></figure><figure className={styles.wksMobile}><Shot name="wks-mobile" alt="De mobiele startpagina van WKS Performance met de knop om in te schrijven" width={390} height={632}/><figcaption>Dezelfde website, op je telefoon.</figcaption></figure></div>
<div className={styles.wksDetail}><div className={styles.projectCopy}><span>Voetbaltraining in Antwerpen</span><p>Een plek waar ouders en spelers de trainingen leren kennen, een pakket kiezen en zich aanmelden.</p><p className={styles.smallCopy}>Ons eigen project. Het aanbod, de prijzen en de volgende stap staan bij elkaar.</p></div><figure><Shot name="wks-services" alt="De trainingspakketten van WKS Performance, met prijzen en knoppen om te boeken" width={1440} height={695}/><figcaption>Van een training kiezen naar een bericht sturen.</figcaption></figure></div>
</article>
<article className={styles.vanloon} aria-labelledby="vanloon-title">
<div className={styles.projectHeading}><div><span className={styles.number}>02</span><h3 id="vanloon-title">Van Loon Badkamers</h3><span className={styles.concept}>Conceptwebsite</span></div><External href={vanloon}>Bekijk het concept</External></div>
<div className={styles.vanloonComposition}><div className={styles.vanloonLeft}><div className={styles.projectCopy}><span>Een voorbeeld voor de renovatiesector</span><p>Het vakwerk voorop. Met ruimte voor foto’s, uitleg over de diensten en een duidelijke offerteaanvraag.</p><p className={styles.smallCopy}>Dit is een demonstratie, geen klantopdracht. De cijfers, beoordelingen en projecten in de beelden zijn illustratief.</p></div><figure className={styles.vanloonMobile}><Shot name="vanloon-mobile" alt="Mobiele conceptwebsite van Van Loon Badkamers met badkamerfoto en offerteknop" width={390} height={844}/><figcaption>Een offerte aanvragen op je telefoon.</figcaption></figure></div><figure className={styles.vanloonDesktop}><div className={styles.browser} aria-hidden="true"><span>•••</span><span>Van Loon Badkamers · concept</span><span>↗</span></div><Shot name="vanloon-desktop" alt="De startpagina van het Van Loon-concept, met een grote badkamerfoto en uitleg over de renovatie" width={1440} height={1250}/></figure></div>
<div className={styles.vanloonDetails}><figure><Shot name="vanloon-services" alt="Het dienstenoverzicht in de conceptwebsite: totaalrenovatie, inloopdouche en tegelwerk" width={1440} height={1361}/><figcaption>De diensten, met beeld en korte uitleg.</figcaption></figure><div><figure><Shot name="vanloon-contact" alt="De afsluitende offerteaanvraag in de conceptwebsite van Van Loon Badkamers" width={1440} height={388}/><figcaption>Een duidelijke volgende stap.</figcaption></figure><p>Je bezoeker ziet wat je doet<br/>en weet waar hij terechtkan.</p></div></div>
</article>
<section className={styles.value} id="website"><h2>Wat jouw website<br/>voor je zaak doet.</h2><div><p className={styles.valueLead}>Klanten kunnen je werk bekijken, je aanbod begrijpen en je makkelijk bereiken.</p><div className={styles.valueColumns}><p>We geven je diensten, foto’s en bestaande klantbeoordelingen een duidelijke plek. Ook op een telefoon blijft alles leesbaar en bereikbaar.</p><p>Jij bezorgt je bedrijfsgegevens en foto’s. Wij bouwen de website, regelen de domeinnaam en hosting en helpen je na de oplevering.</p></div></div></section>
<section className={styles.offer} aria-labelledby="offer-title"><div><h2 id="offer-title">Van je foto’s naar een werkende website.</h2><p>Online in ongeveer 3 werkdagen nadat we je bedrijfsgegevens en foto’s ontvangen. We spreken de inhoud vooraf af. Je bekijkt de website vóór publicatie.</p></div><div className={styles.price}><dl><div><dt>Voorschot</dt><dd>€ 49,99</dd></div><div><dt>Bij oplevering</dt><dd>€ 249,99</dd></div><div><dt>Hosting en ondersteuning</dt><dd>€ 29,99 <span>/ maand</span></dd></div></dl><details><summary>Wat we vooraf afspreken <span aria-hidden="true">+</span></summary><p>Dit startaanbod geldt voor de eerste 5 klanten. Klopt iets niet met de afspraak? Dan passen we het vóór publicatie zonder extra kosten aan.</p><p>Een webshop, maatwerksoftware, fotografie, logo-ontwerp, uitgebreide teksten, advertenties en doorlopende zoekmachineoptimalisatie vallen buiten dit aanbod. Extra pagina’s, betaalde hulpmiddelen en aanpassingen buiten de afspraak krijgen vooraf een aparte prijs.</p></details></div></section>
<section className={styles.closing}><div><h2>Ook zo’n website<br/>voor jouw bedrijf?</h2><p>Vertel ons over je zaak. Je spreekt rechtstreeks met Mohamed.</p></div><External href={wa} className={styles.whatsapp}>Bespreek je website via WhatsApp</External></section>
</main>
<footer className={styles.footer}><span>© 2026 Moza Systems</span><a href="tel:+32451032046">0451 03 20 46</a><a href="mailto:info@mozasystems.com">info@mozasystems.com</a><a href="#inhoud">Naar boven ↑</a></footer>
</div>}
